runtime: python39
service: default
env: standard
# threadsafe: yes

handlers:
  - url: /(.+\.(js|css|png|jpg|gif|svg|json|eot|otf|ttf|woff|woff2))
    static_files: dist/\1
    upload: dist/(.+\.(js|css|png|jpg|gif|svg|json|eot|otf|ttf|woff|woff2))
    secure: always
    redirect_http_response_code: 301

  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico
    secure: always
    redirect_http_response_code: 301

  # Catch all other routes and serve index.html (for Angular routing)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    redirect_http_response_code: 301
